# Generated by Django 2.0.6 on 2018-06-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='link',
            new_name='url',
        ),
    ]
