# Generated by Django 2.0.6 on 2018-06-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0002_auto_20180608_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
