# Generated by Django 2.0.6 on 2018-06-11 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0003_auto_20180608_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('video_id', models.CharField(max_length=15, unique=True)),
                ('votes', models.IntegerField(default=0)),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default=datetime.datetime(2018, 6, 11, 22, 18, 53, 415320, tzinfo=utc), max_length=511),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='video_id',
            field=models.CharField(default='ABC', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
